"""initial schema

Revision ID: 7d45e8539575
Revises: 
Create Date: 2026-07-13 20:38:32.420710
"""
from alembic import op
import sqlalchemy as sa


revision = '7d45e8539575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_kind', 'target_id', 'artifact_type', 'input_hash', 'prompt_version')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('lexeme_id', sa.Integer(), nullable=True),
    sa.Column('position_ms', sa.Integer(), nullable=True),
    sa.Column('subtitle_mode', sa.String(), nullable=True),
    sa.Column('study_mode', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_lexeme', ['lexeme_id'], unique=False)
        batch_op.create_index('ix_event_ts', ['ts'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_status', ['status'], unique=False)

    op.create_table('lexeme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(), nullable=False),
    sa.Column('traditional', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('hsk_level', sa.Integer(), nullable=True),
    sa.Column('is_dict', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simplified')
    )
    op.create_table('media_root',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('include_glob', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('knowledge_state',
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('anki_interval_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('lexeme_id')
    )
    op.create_table('lexeme_stats',
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('encounters', sa.Integer(), nullable=False),
    sa.Column('lookups', sa.Integer(), nullable=False),
    sa.Column('distinct_items', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('lexeme_id')
    )
    op.create_table('saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.create_index('ix_saved_lexeme', ['lexeme_id'], unique=False)

    op.create_table('sense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('traditional', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('glosses', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sense', schema=None) as batch_op:
        batch_op.create_index('ix_sense_lexeme', ['lexeme_id'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level_hint', sa.Integer(), nullable=True),
    sa.Column('cover_item_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['media_root.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_id', 'title')
    )
    op.create_table('anki_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=True),
    sa.Column('saved_item_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('fields_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.ForeignKeyConstraint(['saved_item_id'], ['saved_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('relpath', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('vcodec', sa.String(), nullable=True),
    sa.Column('acodec', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['media_root.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_id', 'relpath')
    )
    op.create_table('playback_progress',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('subtitle_mode', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('text_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('relpath', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('zh', sa.Text(), nullable=False),
    sa.Column('trad', sa.Text(), nullable=True),
    sa.Column('t0_ms', sa.Integer(), nullable=False),
    sa.Column('t1_ms', sa.Integer(), nullable=False),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('en_source', sa.String(), nullable=True),
    sa.Column('align_conf', sa.Float(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['media_item.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['text_track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.create_index('ix_sentence_item_ord', ['item_id', 'ordinal'], unique=False)

    op.create_table('saved_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_item_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['saved_item_id'], ['saved_item.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_item_id', 'sentence_id')
    )
    op.create_table('token_occurrence',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_item.id'], ),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('sentence_id', 'idx')
    )
    with op.batch_alter_table('token_occurrence', schema=None) as batch_op:
        batch_op.create_index('ix_tokocc_item', ['item_id'], unique=False)
        batch_op.create_index('ix_tokocc_lexeme', ['lexeme_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_occurrence', schema=None) as batch_op:
        batch_op.drop_index('ix_tokocc_lexeme')
        batch_op.drop_index('ix_tokocc_item')

    op.drop_table('token_occurrence')
    op.drop_table('saved_context')
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.drop_index('ix_sentence_item_ord')

    op.drop_table('sentence')
    op.drop_table('text_track')
    op.drop_table('playback_progress')
    op.drop_table('media_item')
    op.drop_table('anki_link')
    op.drop_table('series')
    with op.batch_alter_table('sense', schema=None) as batch_op:
        batch_op.drop_index('ix_sense_lexeme')

    op.drop_table('sense')
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_lexeme')

    op.drop_table('saved_item')
    op.drop_table('lexeme_stats')
    op.drop_table('knowledge_state')
    op.drop_table('setting')
    op.drop_table('media_root')
    op.drop_table('lexeme')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_status')

    op.drop_table('job')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_ts')
        batch_op.drop_index('ix_event_lexeme')

    op.drop_table('event')
    op.drop_table('ai_artifact')
    # ### end Alembic commands ###
