// Export tray: preview selected saved items as Anki notes (editable Meaning,
// collection-wide dup detection), then commit — media (clips/stills/TTS) is
// generated by the worker job we poll.

import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";

import { awaitJob, fetchExportPreview, startExport, type ExportEntry } from "../api/queries";
import type { ExportPreview, ExportPreviewItem } from "../api/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

interface RowState {
  include: boolean;
  allowDuplicate: boolean;
  meaning: string;
}

type Phase =
  | { name: "loading" }
  | { name: "preview"; data: ExportPreview }
  | { name: "exporting"; total: number; progress: string }
  | { name: "done"; added: number; skipped: number; errors: string[] }
  | { name: "error"; message: string };

export default function ExportTray({
  savedItemIds,
  onClose,
}: {
  savedItemIds: number[];
  onClose: () => void;
}) {
  const qc = useQueryClient();
  const [phase, setPhase] = useState<Phase>({ name: "loading" });
  const [rows, setRows] = useState<Record<number, RowState>>({});

  useEffect(() => {
    fetchExportPreview(savedItemIds)
      .then((data) => {
        const init: Record<number, RowState> = {};
        for (const it of data.items) {
          init[it.saved_item_id] = {
            include: !it.already_exported && it.duplicates === 0,
            allowDuplicate: false,
            meaning: it.fields.Meaning ?? "",
          };
        }
        setRows(init);
        setPhase({ name: "preview", data });
      })
      .catch((e) => setPhase({ name: "error", message: String(e.message ?? e) }));
  }, [savedItemIds]);

  const includedCount = useMemo(
    () => Object.values(rows).filter((r) => r.include).length,
    [rows],
  );

  const commit = async () => {
    if (phase.name !== "preview") return;
    const entries: ExportEntry[] = phase.data.items
      .filter((it) => rows[it.saved_item_id]?.include)
      .map((it) => ({
        saved_item_id: it.saved_item_id,
        fields: { ...it.fields, Meaning: rows[it.saved_item_id].meaning },
        allow_duplicate: rows[it.saved_item_id].allowDuplicate,
      }));
    setPhase({ name: "exporting", total: entries.length, progress: "queued…" });
    try {
      const { job_id } = await startExport(entries);
      if (!job_id) throw new Error("export already queued");
      const job = await awaitJob(job_id);
      if (job.status === "failed") throw new Error(job.error ?? "export failed");
      const summary = JSON.parse(job.progress ?? "{}");
      const errors = (summary.results ?? [])
        .filter((r: { status: string }) => r.status === "error")
        .map((r: { error?: string }) => r.error ?? "unknown");
      setPhase({ name: "done", added: summary.added ?? 0, skipped: summary.skipped ?? 0, errors });
      void qc.invalidateQueries({ queryKey: ["saved"] });
    } catch (e) {
      setPhase({ name: "error", message: String((e as Error).message ?? e) });
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-h-[85vh] max-w-3xl overflow-hidden border-white/10 bg-[#141a18] text-stone-100">
        <DialogHeader>
          <DialogTitle>Export to Anki</DialogTitle>
          <DialogDescription className="text-stone-500">
            {phase.name === "preview" && (
              <>Deck <span className="text-stone-300">{phase.data.deck}</span> · note type{" "}
                <span className="text-stone-300">{phase.data.model}</span> · clips, stills and word
                audio are attached automatically</>
            )}
            {phase.name === "loading" && "Checking your collection for duplicates…"}
            {phase.name === "exporting" && "Generating media and adding notes…"}
          </DialogDescription>
        </DialogHeader>

        {phase.name === "loading" && (
          <div className="grid gap-2 py-4">
            {savedItemIds.map((id) => (
              <div key={id} className="h-12 animate-pulse rounded-lg bg-white/5" />
            ))}
          </div>
        )}

        {phase.name === "error" && (
          <p className="rounded-lg border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-300">
            {phase.message}
          </p>
        )}

        {phase.name === "preview" && (
          <div className="-mx-1 max-h-[50vh] space-y-2 overflow-y-auto px-1">
            {phase.data.items.map((it) => (
              <PreviewRow
                key={it.saved_item_id}
                item={it}
                state={rows[it.saved_item_id]}
                onChange={(next) =>
                  setRows((prev) => ({ ...prev, [it.saved_item_id]: next }))
                }
              />
            ))}
          </div>
        )}

        {phase.name === "exporting" && (
          <div className="py-6 text-center text-sm text-stone-400">
            <span className="mr-2 inline-block size-4 animate-spin rounded-full border-2 border-teal-400 border-t-transparent align-middle" />
            Exporting {phase.total} note{phase.total === 1 ? "" : "s"}…
          </div>
        )}

        {phase.name === "done" && (
          <div className="space-y-2 py-4 text-sm">
            <p className="text-emerald-300">
              ✓ {phase.added} note{phase.added === 1 ? "" : "s"} added to Anki
              {phase.skipped > 0 && (
                <span className="text-stone-500"> · {phase.skipped} skipped</span>
              )}
            </p>
            {phase.errors.map((e, i) => (
              <p key={i} className="text-red-300">{e}</p>
            ))}
          </div>
        )}

        <DialogFooter>
          {phase.name === "preview" ? (
            <>
              <Button variant="ghost" onClick={onClose} className="text-stone-400">
                Cancel
              </Button>
              <Button
                onClick={() => void commit()}
                disabled={includedCount === 0}
                className="bg-teal-500 text-teal-950 hover:bg-teal-400"
              >
                Export {includedCount} note{includedCount === 1 ? "" : "s"}
              </Button>
            </>
          ) : (
            <Button variant="ghost" onClick={onClose} className="text-stone-400">
              Close
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function PreviewRow({
  item,
  state,
  onChange,
}: {
  item: ExportPreviewItem;
  state: RowState;
  onChange: (next: RowState) => void;
}) {
  const exported = item.already_exported !== null;
  return (
    <div className={`rounded-xl border border-white/8 bg-white/[0.03] p-3 ${state.include ? "" : "opacity-55"}`}>
      <div className="flex items-center gap-3">
        <Checkbox
          checked={state.include}
          disabled={exported}
          onCheckedChange={(v) => onChange({ ...state, include: v === true })}
        />
        <span className="font-zh text-lg text-stone-100">{item.fields.Simplified}</span>
        <span className="text-xs text-stone-500">{item.fields.Pinyin}</span>
        <span className="grow" />
        {exported && <Badge className="bg-white/8 text-stone-400">already in Anki</Badge>}
        {!exported && item.duplicates > 0 && (
          <Badge className="bg-amber-400/15 text-amber-300">
            {item.duplicates} duplicate{item.duplicates === 1 ? "" : "s"}
          </Badge>
        )}
        {item.can_clip && <Badge className="bg-white/6 text-stone-500">clip</Badge>}
        {item.can_image && <Badge className="bg-white/6 text-stone-500">still</Badge>}
      </div>
      {!exported && (
        <div className="mt-2 grid gap-1.5 pl-7">
          <Input
            value={state.meaning}
            onChange={(e) => onChange({ ...state, meaning: e.target.value })}
            placeholder="Meaning"
            className="h-8 border-white/10 bg-black/20 text-sm text-stone-200"
          />
          <p className="truncate font-zh text-xs text-stone-500">{item.fields.Sentence}</p>
          {item.duplicates > 0 && (
            <div className="flex items-start gap-2 text-xs text-stone-500">
              <label className="flex items-center gap-1.5">
                <Checkbox
                  checked={state.allowDuplicate && state.include}
                  onCheckedChange={(v) =>
                    onChange({ ...state, allowDuplicate: v === true, include: v === true ? true : state.include })
                  }
                />
                add anyway
              </label>
              {item.duplicate_meanings[0] && (
                <span className="truncate">existing: “{item.duplicate_meanings[0]}”</span>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
